=== maxstrauch/simple-xml-validator/initial_version/addressbook.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	The root element of the document is the addressbook
	element. It must contain the attribute "of" containing
	the owner name of this address book.
-->
<!ELEMENT addressbook (section+)>
<!ATTLIST addressbook 
	of 			CDATA #REQUIRED
>
	
<!--
	The address book is divided into "sections" for different
	purposes. Each section must specifiy it's purpose.
-->
<!ELEMENT section (person*)>
<!ATTLIST section 
	for 	CDATA #REQUIRED
>

<!--
	A person is the basic address book element. It contains all
	further data and must have a type from the list bellow.
-->
<!ELEMENT person (name?,tel*,mail*,birthday?)>
<!ATTLIST person 
	type 	(friend|mom|dad|brother|roommate|coworker) #REQUIRED
>

<!-- The name of the person -->
<!ELEMENT name (#PCDATA)>

<!-- 
	The telephone number. Using the "type" attribute the
	type of the telephone number (either private or for
	work) can be specified.
-->
<!ELEMENT tel (#PCDATA)>
<!ATTLIST tel 
	type 	(private|business) #REQUIRED
>

<!-- 
	The electronic mail address. Using the "type" attribute 
	the type of the mail address (either private or for
	work) can be specified.
-->
<!ELEMENT mail (#PCDATA)>
<!ATTLIST mail 
	type 	(private|business) #REQUIRED
>

<!--
	The birthday of the person. Since not all persons like
	to tell their actually birth year (and since it is not
	nessesary for birthday congrats) this argument is not
	required.
-->
<!ELEMENT birthday EMPTY>
<!ATTLIST birthday 
	year 	CDATA #IMPLIED
	month 	CDATA #REQUIRED
	day 	CDATA #REQUIRED
>

=== maxstrauch/simple-xml-validator/initial_version/task3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE addressbook SYSTEM "addressbook.dtd">
<addressbook of="Jennifer">
	<section for="childhood">
		<person type="friend">
			<name>Anna</name>
			<tel type="private">+(00)49-080-111</tel>
			<mail type="private">anna@example.org</mail>
			<birthday year="1991" month="11" day="21" />
		</person>
		<person type="friend">
			<name>Maria</name>
			<tel type="private">+(00)49-080-192</tel>
			<birthday year="1992" month="9" day="20" />
		</person>
		<person type="dad">
			<tel type="private">+(00)49-080-921</tel>
			<birthday year="1966" month="3" day="4" />
		</person>
		<person type="mom">
			<tel type="private">+(00)49-080-563</tel>
			<birthday year="1965" month="1" day="12" />
		</person>
		<person type="brother">
			<name>John</name>
			<tel type="private">+(00)49-080-284</tel>
			<mail type="private">john@example.org</mail>
			<birthday year="1990" month="7" day="30" />
		</person>
	</section>
	<section for="college">
		<person type="roommate">
			<name>Miriam</name>
			<tel type="private">+(00)49-080-564</tel>
			<mail type="private">miriam@example.org</mail>
			<mail type="business">miriam@bigbusiness.org</mail>
			<birthday year="1995" month="12" day="24" />
		</person>
		<person type="roommate">
			<name>Tina</name>
			<tel type="private">+(00)49-080-199</tel>
			<mail type="private">tina@example.org</mail>
			<birthday year="1990" month="5" day="9" />
		</person>
	</section>
	<section for="work">
		<person type="coworker">
			<name>Andrew</name>
			<tel type="business">+(00)49-081-11</tel>
			<mail type="business">andrew@acme.com</mail>
			<birthday month="11" day="29" />
		</person>
		<person type="coworker">
			<name>Thomas</name>
			<tel type="business">+(00)49-081-12</tel>
			<mail type="business">thomas@acme.com</mail>
			<birthday month="1" day="19" />
		</person>
		<person type="coworker">
			<name>Aayan</name>
			<tel type="business">+(00)49-081-13</tel>
			<mail type="business">aayan@acme.com</mail>
			<birthday month="2" day="24" />
		</person>
	</section>
</addressbook>
